### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ldd'

### ISSUE THREAD

**Issue by Fansirsqi** [ColdWindScholar/TIK#11]
大佬帮忙看下这是啥问题
```bash
/TIK# python3.11 build.py 
 
 ______  ______   __  __   __ __
/\__  _\/\__  _\ /\ \/\ \ /\ \\ \
\/_/\ \/\/_/\ \/ \ \ \/'/'\ \ \\ \
   \ \ \   \ \ \  \ \ , <  \ \ \\ \_
    \ \ \   \_\ \__\ \ \\`\ \ \__ ,__\
     \ \_\  /\_____\\ \_\ \_\\/_/\_\_/
      \/_/  \/_____/ \/_/\/_/   \/_/
 
Build for Linux
Installing extract-dtb
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: extract-dtb in /var/packages/python311/target/lib/python3.11/site-packages (1.2.3)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Installing pyinstaller
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pyinstaller in /var/packages/python311/target/lib/python3.11/site-packages (6.6.0)
Requirement already satisfied: setuptools>=42.0.0 in /var/packages/python311/target/lib/python3.11/site-packages (from pyinstaller) (68.1.2)
Requirement already satisfied: altgraph in /var/packages/python311/target/lib/python3.11/site-packages (from pyinstaller) (0.17.4)
Requirement already satisfied: pyinstaller-hooks-contrib>=2024.3 in /var/packages/python311/target/lib/python3.11/site-packages (from pyinstaller) (2024.4)
Requirement already satisfied: packaging>=22.0 in /var/packages/python311/target/lib/python3.11/site-packages (from pyinstaller) (24.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Installing pycryptodome
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pycryptodome in /var/packages/python311/target/lib/python3.11/site-packages (3.20.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Installing Requests
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: Requests in /var/packages/python311/target/lib/python3.11/site-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /var/packages/python311/target/lib/python3.11/site-packages (from Requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /var/packages/python311/target/lib/python3.11/site-packages (from Requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /var/packages/python311/target/lib/python3.11/site-packages (from Requests) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in /var/packages/python311/target/lib/python3.11/site-packages (from Requests) (2023.11.17)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Installing rich
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: rich in /var/packages/python311/target/lib/python3.11/site-packages (13.7.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /var/packages/python311/target/lib/python3.11/site-packages (from rich) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /var/packages/python311/target/lib/python3.11/site-packages (from rich) (2.17.2)
Requirement already satisfied: mdurl~=0.1 in /var/packages/python311/target/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich) (0.1.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Installing lxml
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: lxml in /var/packages/python311/target/lib/python3.11/site-packages (5.2.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Traceback (most recent call last):
  File "/volume3/TIK/build.py", line 48, in <module>
    import PyInstaller.__main__
  File "/var/packages/python311/target/lib/python3.11/site-packages/PyInstaller/__init__.py", line 17, in <module>
    from PyInstaller import compat
  File "/var/packages/python311/target/lib/python3.11/site-packages/PyInstaller/compat.py", line 95, in <module>
    is_musl = is_linux and "musl" in subprocess.run(["ldd"], capture_output=True, encoding="utf-8").stderr
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/python311/target/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/packages/python311/target/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/var/packages/python311/target/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ldd'
```

**Comment by ColdWindScholar** [comment]
please run ```sudo apt install ldd``` first
