### ISSUE TITLE
extract.f2fs: No such file or directory

### ISSUE THREAD

**Issue by Ran-Xing** [ColdWindScholar/TIK#38]
```log
  >分解 

  请将文件放于/root/TIK/samsung根目录下！

 [0]- 分解所有文件

 [Img]文件

   [1]- vendor_dlkm.img <F2FS>

   [2]- system.img <F2FS>

   [3]- super.img <SUPER>

   [4]- vendor.img <F2FS>

   [5]- product.img <F2FS>

   [6]- odm.img <F2FS>

   [7]- userdata.img <F2FS>

   [8]- system_ext.img <F2FS>


  [00] 返回  [77] 循环解包  
  --------------------------------------
  请输入对应序号：7
[00:56:20][img]解包userdata.img中...
[00:56:20][f2fs]解包userdata.img中...
Traceback (most recent call last):
  File "run.py", line 1926, in <module>
  File "run.py", line 557, in main
  File "run.py", line 626, in project
  File "run.py", line 1121, in unpack_choo
  File "run.py", line 1769, in unpack
  File "run.py", line 1858, in unpack
  File "utils.py", line 60, in call
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1955, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/root/TIK/bin/Linux/aarch64/extract.f2fs'
[PYI-10682:ERROR] Failed to execute script 'run' due to unhandled exception!
(venv) ➜  TIK 
```

**Comment by qlenlen** [comment]
Extract or repack f2fs is only supported under Linux x86_64. Termux Env missed the counterpart binary.
