### ISSUE TITLE
解压Vendor.img时报错

### ISSUE THREAD

**Issue by ECeternalcat** [ColdWindScholar/TIK#40]
已经按照安装教程进行安装，系统版本Ubuntu20.04 server
vendor来自小米8SE MIUI11 安卓10，官方卡刷包

报错内容如下：
[06:03:30][img]解包vendor.img中...
[06:03:30][ext]解包vendor.img中...
Extracting vendor.img --> vendor
Traceback (most recent call last):
  File "imgextractor.py", line 175, in scan_dir
OSError: [Errno 95] Operation not supported: '/vendor/lib64/libvndfwk_detect_jni.qti.so' -> '/mnt/hgfs/Downloads/TIK/G8441/vendor/app/QDMA/lib/arm64/libvndfwk_detect_jni.qti.so'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 1926, in <module>
  File "run.py", line 557, in main
  File "run.py", line 626, in project
  File "run.py", line 1121, in unpack_choo
  File "run.py", line 1769, in unpack
  File "run.py", line 1835, in unpack
  File "imgextractor.py", line 307, in main
  File "imgextractor.py", line 205, in __ext4extractor
  File "imgextractor.py", line 155, in scan_dir
  File "imgextractor.py", line 155, in scan_dir
  File "imgextractor.py", line 155, in scan_dir
  [Previous line repeated 1 more time]
  File "imgextractor.py", line 188, in scan_dir
OSError: [Errno 95] Operation not supported: '/vendor/lib64/libvndfwk_detect_jni.qti.so' -> '/mnt/hgfs/Downloads/TIK/G8441/vendor/app/QDMA/lib/arm64/libvndfwk_detect_jni.qti.so'
[PYI-19888:ERROR] Failed to execute script 'run' due to unhandled exception!

**Comment by ColdWindScholar** [comment]
give me the file

**Comment by Cathgao** [comment]
你是不是这个共享文件夹空间已经满了

**Comment by ColdWindScholar** [comment]
> 你是不是这个共享文件夹空间已经满了 TIK支持全平台运行，为什么要在虚拟机与主机的共享文件夹里跑呢

我也感觉
